### ISSUE TITLE
 CRITICAL Parse error at line 1, column 1 : possible issue .qgz extension?

### ISSUE THREAD

**Issue by stevefaeembra** [alexbruy/qconsolidate#11]
Noticed that QConsolidate3 seems to fail with a parse error on QGIS 3.2.0 (Mac). This happens when saving to a zip file, either as SHP or GPKG.

I've had a quick look through the code and suspect it may be that there is an assumption that the filename extension is .qgs, although the default extension appears to be .qgz (I had no idea this had changed). I suspect if the project isn't found the XML will be an empty string and give this message.

```
2018-10-10T19:58:29     CRITICAL    Parse error at line 1, column 1:
             error occurred while parsing element
             Traceback (most recent call last):
              File "/Users/steven/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qconsolidate3/consolidatethread.py", line 71, in run
              self.consolidate()
              File "/Users/steven/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qconsolidate3/consolidatethread.py", line 96, in consolidate
              doc = self.loadProject()
              File "/Users/steven/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qconsolidate3/consolidatethread.py", line 174, in loadProject
              raise SyntaxError(msg)
              File "", line None
             SyntaxError: Parse error at line 1, column 1:
             error occurred while parsing element
```

**Comment by alexbruy** [comment]
Please file bugreport to the plugin author. I have no relatation to that plugin.

**Comment by alpter** [comment]
I thought u were the author...
#https://github.com/alexbruy/qconsolidate/issues/12
